package cliente.presentacion;

import javax.swing.JButton;

/**
 * Vista donde se renderizaran los elementos necesarios
 */
public class Vista extends javax.swing.JFrame {

    //Cargamos el controlador y modelo de la presentación
    private Controlador controlador;
    private final Modelo modelo;

    /**
     * Inicializamos la vista con los componetes y las acciones
     *
     * @param claseModelo Modelo que se encutra relacionado con la vista
     */
    public Vista(Modelo claseModelo) {
        modelo = claseModelo;
        initComponents();
        AsignarEventos();
    }

    /**
     * Pemite retornar una sola instancia del controlador
     * 
     * @return Controlador retorna el controlador
     */
    public Controlador getControlador() {
        if (controlador == null) {
            controlador = new Controlador(this);
        }
        return controlador;
    }

    /**
     * Obtenemos el modelo relacionado a la vista
     * 
     * @return Retorna el modelo
     */
    public Modelo getModelo() {
        return modelo;
    }

    /**
     * Asignamos los eventos relacionados a la vista
     */
    public void AsignarEventos() {
        CrearSemaforos.addActionListener(getControlador());
    }

    /**
     * Retornamos la instancia de la clase button
     * 
     * @return Retornamos la instancia del boton crear semaforos
     */
    public JButton getCrearSemaforos() {
        return CrearSemaforos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CrearSemaforos = new javax.swing.JButton();
        CantidadSemaforos = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("framePrincipal"); // NOI18N

        jLabel1.setText("Semaforos");

        CrearSemaforos.setText("Crear Semaforos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CrearSemaforos)
                        .addContainerGap(247, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CantidadSemaforos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(245, 245, 245))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CantidadSemaforos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CrearSemaforos)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("framePrincipal");
        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner CantidadSemaforos;
    private javax.swing.JButton CrearSemaforos;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
